namespace Questionable.Model.V1;

public enum EAetheryteLocation
{
    None = 0,

    Gridania = 2,
    GridaniaArcher = 25,
    GridaniaLeatherworker = 26,
    GridaniaLancer = 27,
    GridaniaConjurer = 28,
    GridaniaBotanist = 29,
    GridaniaAmphitheatre = 30,
    GridaniaAirship = 94,

    Uldah = 9,
    UldahAdventurers = 33,
    UldahThaumaturge = 34,
    UldahGladiator = 35,
    UldahMiner = 36,
    UldahAlchemist = 37,
    UldahWeaver = 47,
    UldahGoldsmith = 50,
    UldahChamberOfRule = 51,
    UldahAirship = 95,
    UldahSapphireAvenue = 125,

    Limsa = 8,
    LimsaAftcastle = 41,
    LimsaCulinarian = 42,
    LimsaArcanist = 43,
    LimsaFisher = 44,
    LimsaMarauder = 48,
    LimsaHawkersAlley = 49,
    LimsaAirship = 93,

    Ishgard = 70,
    IshgardForgottenKnight = 80,
    IshgardSkysteelManufactory = 81,
    IshgardBrume = 82,
    IshgardAthenaeumAstrologicum = 83,
    IshgardJeweledCrozier = 84,
    IshgardSaintReymanaudsCathedral = 85,
    IshgardTribunal = 86,
    IshgardLastVigil = 87,

    Idyllshire = 75,
    IdyllshireWest = 90,

    RhalgrsReach = 104,
    RhalgrsReachWest = 121,
    RhalgrsReachNorthEast = 122,

    Kugane = 111,
    KuganeShiokazeHostelry = 112,
    KuganePier1 = 113,
    KuganeThavnairianConsulate = 114,
    KuganeMarkets = 115,
    KuganeBokairoInn = 116,
    KuganeRubyBazaar = 117,
    KuganeSekiseigumiBarracks = 118,
    KuganeRakuzaDistrict = 119,
    KuganeAirship = 120,

    FringesCastrumOriens = 98,
    FringesPeeringStones = 99,
    PeaksAlaGannha = 100,
    PeaksAlaGhiri = 101,
    LochsPortaPraetoria = 102,
    LochsAlaMhiganQuarter = 103,
    RubySeaTamamizu = 105,
    RubySeaOnokoro = 106,
    YanxiaNamai = 107,
    YanxiaHouseOfTheFierce = 108,
    AzimSteppeReunion = 109,
    AzimSteppeDawnThrone = 110,
    AzimSteppeDhoroIloh = 128,

    DomanEnclave = 127,
    DomanEnclaveNorthern = 129,
    DomanEnclaveSouthern = 130,
    DomanEnclaveDocks = 162,

    Crystarium = 133,
    CrystariumMarkets = 149,
    CrystariumThemenosRookery = 150,
    CrystariumDossalGate = 151,
    CrystariumPendants = 152,
    CrystariumAmaroLaunch = 153,
    CrystariumCrystallineMean = 154,
    CrystariumCabinetOfCuriosity = 155,

    Eulmore = 134,
    EulmoreMainstay = 157,
    EulmoreNightsoilPots = 158,
    EulmoreGloryGate = 159,
    EulmoreSoutheastDerelict = 135,

    LakelandFortJobb = 132,
    LakelandOstallImperative = 136,
    KholusiaStilltide = 137,
    KholusiaWright = 138,
    KholusiaTomra = 139,
    AmhAraengMordSouq = 140,
    AmhAraengInnAtJourneysHead = 161,
    AmhAraengTwine = 141,
    RaktikaSlitherbough = 142,
    RaktikaFanow = 143,
    IlMhegLydhaLran = 144,
    IlMhegPiaEnni = 145,
    IlMhegWolekdorf = 146,
    TempestOndoCups = 147,
    TempestMacarensesAngle = 148,

    OldSharlayan = 182,
    OldSharlayanStudium = 184,
    OldSharlayanBaldesionAnnex = 185,
    OldSharlayanRostra = 186,
    OldSharlayanLeveilleurEstate = 187,
    OldSharlayanJourneysEnd = 188,
    OldSharlayanScholarsHarbor = 189,

    RadzAtHan = 183,
    RadzAtHanMeghaduta = 191,
    RadzAtHanRuveydahFibers = 192,
    RadzAtHanAirship = 193,
    RadzAtHanAlzadaalsPeace = 194,
    RadzAtHanHallOfTheRadiantHost = 195,
    RadzAtHanMehrydesMeyhane = 196,
    RadzAtHanKama = 198,
    RadzAtHanHighCrucible = 199,

    LabyrinthosArcheion = 166,
    LabyrinthosSharlayanHamlet = 167,
    LabyrinthosAporia = 168,
    ThavnairYedlihmad = 169,
    ThavnairGreatWork = 170,
    ThavnairPalakasStand = 171,
    GarlemaldCampBrokenGlass = 172,
    GarlemaldTertium = 173,
    MareLamentorumSinusLacrimarum = 174,
    MareLamentorumBestwaysBurrow = 175,
    ElpisAnagnorisis = 176,
    ElpisTwelveWonders = 177,
    ElpisPoietenOikos = 178,
    UltimaThuleReahTahra = 179,
    UltimaThuleAbodeOfTheEa = 180,
    UltimaThuleBaseOmicron = 181
}
